runtime: nodejs10
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
env_variables:
  TARGET_ENVIRONMENT: "#####"
  DATABASE_USERNAME: "#####"
  DATABASE_PASSWORD: "#####"
  DATABASE_NAME: "#####"
  DATABASE_HOST: "#####"
  DATABASE_PORT: ""
  CORS_ALLOWED_ORIGINS: "#####"